#!/system/bin/sh
# AutoPurge Pro - Main Service

MODDIR="/data/adb/modules/Clear_Rubbish"
[ -d "/data/adb/ksu/modules/Clear_Rubbish" ] && MODDIR="/data/adb/ksu/modules/Clear_Rubbish"

export LD_LIBRARY_PATH="$MODDIR:$LD_LIBRARY_PATH"
chmod 755 "$MODDIR/MainControl"
nohup "$MODDIR/MainControl" > /dev/null 2>&1 &
