#!/system/bin/sh
# AutoPurge Pro - Log Service

MODDIR="/data/adb/modules/Clear_Rubbish"
[ -d "/data/adb/ksu/modules/Clear_Rubbish" ] && MODDIR="/data/adb/ksu/modules/Clear_Rubbish"

export LD_LIBRARY_PATH="$MODDIR:$LD_LIBRARY_PATH"
chmod 755 "$MODDIR/LogClear"
nohup "$MODDIR/LogClear" > /dev/null 2>&1 &
